<?php

namespace AppBundle\Repository;

/**
 * RowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RowRepository extends \Doctrine\ORM\EntityRepository
{
}
